### ISSUE TITLE
Create a napkin diagram and architecture

### ISSUE THREAD

**Issue by vinayakasg18** [airavata-courses/DCoders#1]
Technical story
- Understand the use cases.
- Create a basic diagram on the understanding of the use cases.
- Each team member to create a napkin diagram
- Decide on the final diagram and create a PR to merge to master

**Comment by vinayakasg18** [comment]
Meeting Overview,
01/19/2022
- As a first meeting, we brainstormed on the project idea to understand the basic need for the first iteration and what all the 
   services required.
- Discussion on project strategies and the role of each team member.
- How to communicate on GitHub and create stories, issues, and bugs.
- Created a wiki page.
- Team to come back with the napkin diagram and architecture of the project.

**Comment by SwetShah** [comment]
Guys, I have created a napkin diagram. Let me know what do you guys think.
![Napkin Diagram](https://user-images.githubusercontent.com/31665290/151297067-778a523c-5137-4f5d-9e3e-239e3882b3e5.jpeg)

**Comment by vinayakasg18** [comment]
Looks good but mostly aligns with the architecture diagram(need to include other technical details though). Think of explaining the project to someone who doesn't have any idea about the technologies in a single diagram.

**Comment by SwetShah** [comment]
Good suggestion. Let me refactor the same

**Comment by SwetShah** [comment]
Please find below the refactored diagram

![Napkin_2](https://user-images.githubusercontent.com/31665290/151483467-43ec4762-9ff7-413b-b991-994442c30f7e.jpeg)

**Comment by vinayakasg18** [comment]
Looks good. But I feel the windows could have had some information related to weather. Otherwise, it is a bit difficult to understand.

**Comment by vinayakasg18** [comment]
![NapKinDiagram2](https://user-images.githubusercontent.com/52463165/151484266-1b8cf105-b0b6-4250-bd44-a69ec30289ed.png)
How about this?.

**Comment by SwetShah** [comment]
Looks good to me

**Comment by SwetShah** [comment]
What do you think for the following

![Napkin_3](https://user-images.githubusercontent.com/31665290/151484528-d028271f-b843-4996-8639-b5399376df19.jpeg)

**Comment by vinayakasg18** [comment]
> What do you think for the following
> 
> ![Napkin_3](https://user-images.githubusercontent.com/31665290/151484528-d028271f-b843-4996-8639-b5399376df19.jpeg)

Much better.  I'm okay with this.
@ChaitanyaD20, what do you say?

**Comment by ChaitanyaD20** [comment]
Yes, the 2nd (refactored) diagram is better is it conveys meaning in a better way.

**Comment by vinayakasg18** [comment]
Once we have finalized the napkin diagram. Please commit to the main branch by following the below commit message template. Commit directly to the main branch allowed only this time since it is not a code change. I will be making changes to restrict what commits go into main.
#1-<issue_name/feature_name>: Short commit message

**Comment by ChaitanyaD20** [comment]
I am also uploading an architecture diagram representing the workflow with initial team responsibilities, kindly have a check and let me know:

UI --> Gateway[Node.js][Chaitanya] <--> User Management [Java] [SQL/Mongo] [Swet]
		  |
		  |
		  |
	  Data Source  --> fetches NASA data from AWS cloud [Python] [Vinayak]
	          |										
	          |		
	          |										
    Storage Service  --> DB [Go] [Mongo]
                  |
                  |
                  |
    Caching Service (Redis)
                  |
                  |
                  |
     Metadata/Audit (Mongo)

**Comment by SwetShah** [comment]
Looks great for the initial phase. Might have to do some amendments during the process.

**Comment by vinayakasg18** [comment]
Team,
We need to push our architecture diagram to GitHub. Let's have a meeting set up to go through again and commit to GitHub.
