### ISSUE TITLE
Project 1 Review (Scapsulators)

### ISSUE THREAD

**Issue by shubhpatr** [airavata-courses/DCoders#18]
Just ran your project, It was not clear how to run the project, had to figure out the branch myself. 

I'm running the project from feature/3-user-management-service.

 On build getting this error : -

Error: Unable to access jarfile target/UserManagement-0.0.1-SNAPSHOT.jar 

Do I need to have some prerequisite setup? Let me know if I am doing something wrong. 

Reviewed by Team Scapsulators (https://github.com/airavata-courses/scapsulators)

**Comment by vinayakasg18** [comment]
Hello Shubham,
Thank you for the review. We haven't merged all the branches to main yet. Have you tried already remote docker images?.

Let me know if you are able to run.

**Comment by pranavacharya** [comment]
Hello, I tried to run your project now. I also found it difficult to follow through the WIKI document https://github.com/airavata-courses/DCoders/wiki/local-runbook as mentioned by @shubhpatr  

Can you provide steps to run remote docker images ?

Thanks.
Team Garuda

**Comment by vinayakasg18** [comment]
The commands are given on the same page. You need to have the docker installed on your machine (That's the prereq). 
https://github.com/airavata-courses/DCoders/wiki/local-runbook#follow-the-below-steps-to-run-the-application-locally 

- User Management: Replace {docker_host} with the docker hostname
- Rest of the applications runs as it is (copy and paste the command).

**Comment by pranavacharya** [comment]
Got it, thanks. 

Maybe a note about which branch to checkout before each module might be helpful on https://github.com/airavata-courses/DCoders/wiki/local-runbook 

Had to refer other parts of WIKI to figure it out. 

Thanks,
Team Garuda

**Comment by vinayakasg18** [comment]
Got it. Thanks for the review. Will make the changes. 👍

**Comment by vinayakasg18** [comment]
> Just ran your project, It was not clear how to run the project, had to figure out the branch myself.
> 
> I'm running the project from feature/3-user-management-service.
> 
> On build getting this error : -
> 
> Error: Unable to access jarfile target/UserManagement-0.0.1-SNAPSHOT.jar
> 
> Do I need to have some prerequisite setup? Let me know if I am doing something wrong.
> 
> Reviewed by Team Scapsulators (https://github.com/airavata-courses/scapsulators)

Fixed the docker-compose issue. Could you please check if it is working for you now?.

**Comment by vinayakasg18** [comment]
Resolved the docker-compose, and Mapbook M1 chip docker issue.
