### ISSUE TITLE
Project review (Viyad)

### ISSUE THREAD

**Issue by renuka-srishti** [airavata-courses/DCoders#19]
Good work on https://github.com/airavata-courses/DCoders/wiki/Git-branching-and-release-strategy
I did not see in any other project.
Well explained https://github.com/airavata-courses/DCoders/wiki/local-runbook

Later improvement: User authorization can be added in next milestone.

**Comment by renuka-srishti** [comment]
I tried running UserManagement service, running fine.

**Comment by vinayakasg18** [comment]
Thanks a lot for the feedback.
