### ISSUE TITLE
Peer Review (Dexlab)

### ISSUE THREAD

**Issue by saurabh737** [airavata-courses/DCoders#20]
[Wiki](https://github.com/airavata-courses/DCoders/wiki/local-runbook) was helpful and we are able to run all the services smoothly.

Future Improvements:-
1. Alert can be improvised instead of simply displaying on the browser.
2. Security - Users can access the history of other users by putting their uniqueid's.
3. Plot image is not well aligned on the page.

**Comment by vinayakasg18** [comment]
Thank you for the feedback. Mentioned issues are already on a backlog and we will fix those. We have kept the implementation very basic for milestone1.
